homepage:
   path: /
   controller: App\Controller\DefaultController::homepage


category:
   path: /category-{id}
   controller: App\Controller\DefaultController::category

product:
   path: /product-{id}
   controller: App\Controller\DefaultController::product

